### PR TITLE
Fix done button behaviour in username field in AddUserActivity

### PR DESCRIPTION
**Pull request by Etav99**
done button in keyboard now causes call to addUser button onClick method.

### CODE REVIEW

**Comment by Etav99** [comment]
[W AddFace nie działa klawiaturowy "Enter" - powoduje on kliknięcie przycisku "Anuluj"](https://trello.com/c/e36jNuwa/33-w-addface-nie-dzia%C5%82a-klawiaturowy-enter-powoduje-on-klikni%C4%99cie-przycisku-anuluj)

**Review by Qubaef — CHANGES_REQUESTED** [review]
First of all, fix commit name to start with capital letter.
Secondly, I have tested the functionality and it still seems uncomfortable. Clicking the enter button should hide the keyboard and still let me modify values until I proceed manually. Right know it just proceeds by itself and leaves me with no option. I believe that there should be no action taken after the click - just hiding the keyboard.

**Review by Qubaef — COMMENTED** [review]
After clicking "enter" on the keyboard, app still behaves like clicking "confirm" button

**Review by Qubaef — APPROVED** [review]
Works perfectly now

**Pull request merged**
